# Vi mode
set -o vi

# Environment variables
export EDITOR=vim

# Terminal prompt
export PS1="\u@\h:\w\$ "

# Displays date and time for history command
export HISTTIMEFORMAT='%F %T '

# Ignore duplicates in history
export HISTCONTROL=ignoredups:erasedups

# Aliases
if [ -f ~/.bash/bash.alias ];
then
    source ~/.bash/bash.alias
fi

# Local settings
if [ -f ~/.bash/bash_profile.local ];
then
    source ~/.bash/bash_profile.local
fi

# vim: set syntax=sh :
